### ISSUE TITLE
有movenet的与训练模型吗？是否有将movenet的网络模型转换为onnx模型的代码？

### ISSUE THREAD

**Issue by APeiZou** [lee-man/movenet#1]
有movenet的与训练模型吗？是否有将movenet的网络模型转换为onnx模型的代码？@lee-man

**Comment by APeiZou** [comment]
Are there movenet’s pretrained models? Is there any code to convert movenet's network model to onnx model?@lee-man

**Comment by lee-man** [comment]
@APeiZou 暂时还没有。现在训练和测试还有一些问题。

**Comment by APeiZou** [comment]
@Lee-man  训练和测试哪里还有问题呢？

**Comment by lee-man** [comment]
> @lee-man 训练和测试哪里还有问题呢？

CenterNet里头训pose estimation用的是object detection预训练的模型，movenet这边对应的mobilenet+FPN的预训练模型我还没找到。测试这块原来是multi-person，应该是要改成single-person。你要是有看code欢迎帮助改进。

**Comment by APeiZou** [comment]
@lee-man movenet网络我看损失函数只有三个头组成吗？跟官方的说明文档的4个head的不太符合啊，coco数据集本身就是多人姿态估计的数据集啊。不是可以运用多人姿态估计测试吗？

**Comment by APeiZou** [comment]
@lee-man sigmoid_()和_sigmoid()和nn.sigmoid()函数有什么不同啊？

**Comment by lee-man** [comment]
> @lee-man movenet网络我看损失函数只有三个头组成吗？跟官方的说明文档的4个head的不太符合啊，coco数据集本身就是多人姿态估计的数据集啊。不是可以运用多人姿态估计测试吗？

多人姿态测试可能有带来一些false positives. 另外，几个predictor head的问题我再检查下code再与你交流。

**Comment by lee-man** [comment]
> @lee-man movenet网络我看损失函数只有三个头组成吗？跟官方的说明文档的4个head的不太符合啊，coco数据集本身就是多人姿态估计的数据集啊。不是可以运用多人姿态估计测试吗？

其实现在的设定movenet是有6个prediction head组成的，和centernet里头一样，多的还包括bounding box回归，center point offset。然后还有个区别是movenet的keypoint offset应该是2*17个channel，现在的实现只有2个channel，不同keypoint share同一个。

**Comment by APeiZou** [comment]
@lee-man 关于movenet的6个head的细节代码在哪个文件夹里面方便告诉一下吗？是如何只通过关节点坐标来制作的ground-truth的标签的？

**Comment by APeiZou** [comment]
@lee-man 关于movenet的6个head的细节代码在哪个文件夹里面方便告诉一下吗？是如何只通过关节点坐标来制作的ground-truth的标签的？

**Comment by lee-man** [comment]
6个head的定义在[opt.py](https://github.com/lee-man/movenet/blob/main/src/lib/opts.py#L324)，所有的option都是开的 所以有6个。ground-truth你可以看[multi_pose](https://github.com/lee-man/movenet/blob/main/src/lib/datasets/sample/multi_pose.py).

**Comment by hematank** [comment]
请问一下，trains\multipose.py\下的batch是在哪个文件赋值的，在coco_hp.py么，可我在coco_hp.py中没有看到赋值，谢谢解答一下~

**Comment by lee-man** [comment]
@hematank MultiPoseTrainer父类是 base trainer，在里头有
