### ISSUE TITLE
Structure of Training Images

### ISSUE THREAD

**Issue by j4y33** [lee-man/movenet#14]
Hi Lee, 

What is the expected file-structure for the training images, the labels and the "reference" between the two, to put into _Active_ folder? 

I have coco annotations for many consecutive frames in a .json and the images separately with only reference between those two being the filepath/name. I have attached a json file for a single frame for clarity.

Help would be greatly appreciated! 

Thanks and best regards.
Julian
[kkp_single_frame.txt](https://github.com/lee-man/movenet/files/8579896/kkp_single_frame.txt)

**Comment by lee-man** [comment]
I use the same format as the COCO.
