### ISSUE TITLE
training error when loading the pth model

### ISSUE THREAD

**Issue by mu0072** [lee-man/movenet#16]
Hello, Lee. Thanks for your amazing work. I've got the following errors when I tried to train the model:

> Creating model...
> Skip loading parameter backbone.body.6.conv.2.weight, required shapetorch.Size([56, 336, 1, 1]), loaded shapetorch.Size([32, 192, 1, 1]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
> Skip loading parameter backbone.body.16.conv.2.weight, required shapetorch.Size([280, 1680, 1, 1]), loaded shapetorch.Size([160, 960, 1, 1]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
> Skip loading parameter backbone.body.11.conv.1.0.bias, required shapetorch.Size([672]), loaded shapetorch.Size([384]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
> Skip loading parameter backbone.body.5.conv.2.bias, required shapetorch.Size([56]), loaded shapetorch.Size([32]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
> Skip loading parameter backbone.body.16.conv.2.bias, required shapetorch.Size([280]), loaded shapetorch.Size([160]). If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
...
The conda env is cuda10.2, toch 1.9.0, and torchvision 0.10.0.  It seems the shapes were not match? 
Any suggestions? Thanks.

**Comment by lee-man** [comment]
Hi @mu0072,

Sorry for the late reply. Since this repo is no longer maintained, I am not sure what exactly the problem is in your case.
However, I am sure that if you try the previous version, e.g., commit 847a9e84b56cc7a5550a38f1651fbb315a4dd92e, it might work.

Min

**Comment by mu0072** [comment]
Thanks so much @lee-man . I will have a try.
