### ISSUE TITLE
Where can I get the movenet paper? 😂

### ISSUE THREAD

**Issue by ElieenAndBella** [lee-man/movenet#19]

**Comment by ElieenAndBella** [comment]
Where can I get the Pose-Dataset?
![image](https://user-images.githubusercontent.com/54427695/195628675-f2ace116-dd62-409a-b435-9a5a881b36f5.png)
Is the Pose-Dataset in the picture?

**Comment by lee-man** [comment]
1. MoveNet is originally a project from Google, and it's not a research project.
2. You may create the dataset by yourself. Currently the dataset I use is not open-sourced.
