### ISSUE TITLE
交流一下

### ISSUE THREAD

**Issue by fire717** [lee-man/movenet#2]
作者你好，我最近也在尝试自己用pytorch复现movenet，咱们可以一起交流讨论下。

我是参考的tflite模型的结构，目前我主要有几个不是很清楚的，先抛出来

1. 模型的header之后有很多复杂的op操作，据我观察分析也大概看出来作用了，比如有argmax等，我的疑问之一就是，这些op咱们需要写在pytorch的网络结构中吗？如果要写，那估计还要实现argmax等不支持op的反向传播的求导，同时部署转换onnx估计也会遇到不支持的op，所以我目前的方案是网络结构到4个header的conv就结束，后处理代码里实现。不知道这样会不会影响结果；
2. 模型的数据gt如何构造，或者说loss如何计算，如果把后处理全写到网络中，那么似乎直接计算输出的关键点坐标的回归loss即可，但是显然不显示，从aux loss提升精度、多任务训练提升精度等方面考虑都是要用中间输出的。那么问题就是用哪些，我目前就是直接用conv输出的数据去和相应生成的gt计算mseloss，但是貌似没啥效果，感觉中间层还要再处理下
3. 模型中一些常量意义不明，比如name: mul_2中的一个48*48的矩阵，其值不知道从何而来，感觉像是不同像素点的权重；又比如通过center点+reg回归点得到的关键点坐标，x、y分别减去了一个横向递增和纵向递增的矩阵，经过分析加上后面的平方我感觉是要把关键点位置置0最小，那么这么做意义是什么？凸显特征点的值？后面加了一个1.8，我猜测是防止除以0，那么这个1.8又是如何得到的？应该是有一个理论下界的，比如经过减去递增矩阵后如何如何

暂时想到这几个，希望能交流一下，网上相关的讨论太少了，论文没有、知乎没有，就一个官方介绍的博客，实在不好搞

**Comment by fire717** [comment]
backbone就不说了很简单，然后header我看你这里的代码也是直接输出conv就行了。不知道效果如何？
还有fc.bias.data.fill_(-2.19)这个值是如何来的呢？

**Comment by lee-man** [comment]
> 作者你好，我最近也在尝试自己用pytorch复现movenet，咱们可以一起交流讨论下。
> 
> 我是参考的tflite模型的结构，目前我主要有几个不是很清楚的，先抛出来
> 
> 1. 模型的header之后有很多复杂的op操作，据我观察分析也大概看出来作用了，比如有argmax等，我的疑问之一就是，这些op咱们需要写在pytorch的网络结构中吗？如果要写，那估计还要实现argmax等不支持op的反向传播的求导，同时部署转换onnx估计也会遇到不支持的op，所以我目前的方案是网络结构到4个header的conv就结束，后处理代码里实现。不知道这样会不会影响结果；
> 2. 模型的数据gt如何构造，或者说loss如何计算，如果把后处理全写到网络中，那么似乎直接计算输出的关键点坐标的回归loss即可，但是显然不显示，从aux loss提升精度、多任务训练提升精度等方面考虑都是要用中间输出的。那么问题就是用哪些，我目前就是直接用conv输出的数据去和相应生成的gt计算mseloss，但是貌似没啥效果，感觉中间层还要再处理下
> 3. 模型中一些常量意义不明，比如name: mul_2中的一个48*48的矩阵，其值不知道从何而来，感觉像是不同像素点的权重；又比如通过center点+reg回归点得到的关键点坐标，x、y分别减去了一个横向递增和纵向递增的矩阵，经过分析加上后面的平方我感觉是要把关键点位置置0最小，那么这么做意义是什么？凸显特征点的值？后面加了一个1.8，我猜测是防止除以0，那么这个1.8又是如何得到的？应该是有一个理论下界的，比如经过减去递增矩阵后如何如何
> 
> 暂时想到这几个，希望能交流一下，网上相关的讨论太少了，论文没有、知乎没有，就一个官方介绍的博客，实在不好搞

1. 对于后处理，我也是仿照centernet的方法，单独实现在encode.py里头的，这个你可以看下那边的代码。最后要转onnx我估摸着是要单独再写个model定义，把后处理加进去一块儿转。
2. gt的构造我现在都是按centernet来的，跟movenet的文档里说的还有细微差别。我个人建议还是在训练的时候先不把后处理加进去，这样输出的就只是几个heatmap。
3. 你去看了movenet开源的模型参数里是吧？这部分类似的功能我也是实现在encode.py里头了。按他们文档的意思，第一个center point的预测要按乘上和图片中心距离的权重，keypoint heatmap也要乘上regression得到的点的距离的权重。这一部分我就按自己理解实现了一下，估计和movenet本来实现还是有很大差距的。1.8应该就是为了保证计算稳定性，并且控制递减速度。我们关于这一点可以再讨论讨论。我还没深入看movenet开源模型的参数。

这几天没花时间搞这个，我们可以加微信方便之后交流。我微信是minli_amoy

**Comment by lee-man** [comment]
> backbone就不说了很简单，然后header我看你这里的代码也是直接输出conv就行了。不知道效果如何？
> 还有fc.bias.data.fill_(-2.19)这个值是如何来的呢？

我试了下，现在模型有点效果，但是挺一般的。
-2.19按照centernet里头的定义来，我没改。

**Comment by fire717** [comment]
谢谢答复！你说的”按他们文档的意思，第一个center point的预测要按乘上和图片中心距离的权重“，然后我可视化尝试了下，果然如此，解决了我的一个大疑惑，目前后处理全流程我基本了解了。就是不知道数据构造和loss方面的细节了

`data = np.load("truediv_2add_1.npy").reshape(48,48)
img = (data-np.min(data))/(np.max(data)-np.min(data))*255
cv2.imwrite('t.jpg',img)`

你说的他们的文档，方便给个连接吗？我感觉你说的这些东西我都没看到过，我只看到一个博客文章：
[Next-Generation Pose Detection with MoveNet and TensorFlow.js](https://blog.tensorflow.org/2021/05/next-generation-pose-detection-with-movenet-and-tensorflowjs.html)
然后就是tfhub里开源的tflite模型。我目前手里能参考的只有这两个东西
