### ISSUE TITLE
batch_size大小设置问题

### ISSUE THREAD

**Issue by Blankit** [lee-man/movenet#4]
作者你好。在movenet/experiments/single_pose_movenet_coco.sh文件里，看您设置的batch_szie=24,使用的是4个gpu。我在训练的时候，设置batch_szie=24，观察显存占用的非常的少。想问您，如果方便，麻烦回答一下，这里的batch_size实际训练时给的是多少，相应的学习率是多少？

**Comment by lee-man** [comment]
你好，我这边还没试batch_size和学习率，24只是随意设的一个值。具体设啥可以看显存占用相应调高。
