### ISSUE TITLE
COCO数据集单人姿态

### ISSUE THREAD

**Issue by Victcode** [lee-man/movenet#5]
您好，麻烦请教个问题，请问原始COCO数据集能直接做单人姿态训练吗。
src/lib/datasets/dataset/coco_hp.py中self.max_objs = 32，我理解的并不是单人的

**Comment by lee-man** [comment]
用filter_hp.py可以过滤coco的数据集，保证数据里头人数少于2.同时我定义了应该dataset，叫active。你可以看一下。
