### ISSUE TITLE
Can the trained model be used in the official Google Repo?

### ISSUE THREAD

**Issue by jgcbrouns** [lee-man/movenet#7]
Great work on this repo! I have 2 questions. 

1. Can the model be converted to a compatible format that can be used in the original [repository](https://www.tensorflow.org/hub/tutorials/movenet )?
2. How long does training take and how many images should be in the trainingset to yield accurate results?

My goal is to retrain a MoveNet model and use it for inference in the TFLite.js browser. As to my understanding, Google only provides examples on how to use the models (that they provide), but do not provide the trainingscode.

I look forward hearing from you.

**Comment by lee-man** [comment]
Hi @jgcbrouns ,

For the inference, you can refer to my another repo: https://github.com/lee-man/movenet-pytorch
Currently, that codebase supports the conversion from Pytorch to TFLite model, and can be used in the original Android demo. I am not sure whether it can be used in JS.

For the second question, we are still exploring different training settings, and still cannot get a satisfactory performance. Thanks!
